name: NuGet Update Alert

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: Check for Updates
        run: dotnet outdated MSSAMortgageCalculator --include "MSSAMortgageCalculator"

      - name: Send Alert
        run: |
          updated_packages=$(dotnet outdated -u -j)
          if [ -n "$updated_packages" ]; then
            echo "Glizzies available:"
            echo "$updated_packages"
            curl -X POST -H "Content-Type: application/json" -d '{
              "content": "NuGet package updates available:\n```'"$updated_packages"'\n```"
            }' $DISCORD_WEBHOOK_URL
          else
            echo "No Glizzies today..."
          fi
        env:
