name: NuGet Update Alert

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 1-5"

jobs:
  update-alert:
    runs-on: ubuntu-latest

    steps: #checkout current repo
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x

      - name: Tools #install tool that will enable version checking
        id: tools
        run: dotnet tool install --global dotnet-outdated-tool

      - name: Send Alert #send alert through discord webhook
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.GLIZZYUPDATES_WEBHOOK_URL }}
        run: | #check the .csproj for a MSSAMortgageCalculator package
          OUTPUT=$(dotnet-outdated --include MSSAMortgageCalculator GlizzyGlobal/GlizzyGlobal/GlizzyGlobal.csproj) 
          if [[ $OUTPUT =~ "No outdated dependencies" ]]; then
            echo "NugGet package updates not available:"
            curl -X POST -H "Content-Type: application/json" \
              -d '{"content": "No glizzies today..."}' \
              "$DISCORD_WEBHOOK_URL"
          else
            echo "NuGet package updates are available:"
            curl -X POST -H "Content-Type: application/json" \
              -d '{"content": "Come get your Glizzies!!!"}' \
              "$DISCORD_WEBHOOK_URL"
          fi
